exec-once = swww-daemon
exec-once = swww-restore
exec-once = launch-waybar
exec-once = wl-paste --type text  --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = Telegram -startintray
exec-once = mako
exec-once = systemctl --user start pipewire wireplumber pipewire-pulse
