decoration {
    rounding = 10
    rounding_power = 2

    active_opacity = 0.83
    inactive_opacity = 0.80

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }

    blur {
        enabled = true
        size = 4
        passes = 4
	new_optimizations = true
	xray = true
	popups = true

        vibrancy = 0.2
    }
}
